[package]
name = "hexagon-bridge"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[lib]
name = "hexagon_bridge"
crate-type = ["cdylib"]

[dependencies]
hexagon-vm-core = { path = "../hexagon-vm-core" }
serde_json = "1"
rmp-serde = "0.13"

[features]
active_import = []
